# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{with_filled_field_scope}
  s.version = "1.0.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Marcin Nowicki"]
  s.date = %q{2010-03-08}
  s.description = %q{Adds with_filled_field scope to active record models. It scope searches for record with specified field filled.}
  s.email = %q{pr0d1r2@doubledrones.com}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.rdoc"
  ]
  s.files = [
    ".document",
     ".gitignore",
     "LICENSE",
     "README.rdoc",
     "Rakefile",
     "VERSION",
     "lib/with_filled_field_scope.rb",
     "spec/spec.opts",
     "spec/spec_helper.rb",
     "spec/with_filled_field_scope_spec.rb",
     "with_filled_field_scope.gemspec"
  ]
  s.homepage = %q{http://github.com/Pr0d1r2/with_filled_field_scope}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{Adds with_filled_field scope to active record models}
  s.test_files = [
    "spec/spec_helper.rb",
     "spec/with_filled_field_scope_spec.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_development_dependency(%q<active_record_connectionless>, [">= 1.0.2"])
    else
      s.add_dependency(%q<rspec>, [">= 1.2.9"])
      s.add_dependency(%q<active_record_connectionless>, [">= 1.0.2"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 1.2.9"])
    s.add_dependency(%q<active_record_connectionless>, [">= 1.0.2"])
  end
end

